In [30]:
import pandas as pd
df = pd.read_csv("output.csv")
df = df.drop(["Unnamed: 0"], axis=1)

In [31]:
df.groupby("Characters").count().sort_values(by="Quotes", ascending=False).head(10)

            Quotes
Characters
FRY           2629
BENDER        2322
LEELA         2086
FARNSWORTH     985
ZOIDBERG       567
AMY            480
HERMES         391
ZAPP           330
KIF            190
CALCULON       106

In [32]:
mask = (df['Quotes'].str.len() >22)
df2 = df.loc[mask]

In [33]:
def character_check(x):
    if x[:8] == "ZOIDBERG":
        return x[:8]
    
    elif x[:3] == "FRY":
        return x[:3]
    elif x[:5] == "LEELA":
        return x[:5]
    elif x[:6] == "BENDER":
        return x[:6]
    elif x[:10] == "FARNSWORTH":
        return x[:10]
    elif x[:3] == "AMY":
        return x[:3]
    elif x[:6] == "HERMES":
        return x[:6]
    elif x[:4] == "ZAPP":
        return x[:4]
    else:
        return x


df2['Characters_consolidated'] = df.apply(lambda row: character_check(row['Characters']), axis=1)

/Users/arjun.maniyar/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [34]:
df2.groupby("Characters_consolidated").count().sort_values(by="Quotes", ascending=False).head(10)

                         Characters  Quotes
Characters_consolidated
FRY                            1970    1970
BENDER                         1804    1804
LEELA                          1643    1643
FARNSWORTH                      829     829
ZOIDBERG                        434     434
AMY                             325     325
HERMES                          307     307
ZAPP                            283     283
KIF                             146     146
CALCULON                         90      90

In [35]:
df3 = df2.groupby("Characters_consolidated").count().sort_values(by="Quotes", ascending=False).head(10)

In [36]:
df2.sort_values(by=["Characters_consolidated"], ascending=False)

,Characters,Quotes,Characters_consolidated
13146,ZOOKEEPER,Fool! A quip without putting me behind bars wo...,ZOOKEEPER
13144,ZOOKEEPER,"Later, if anyone asks how I got away, tell the...",ZOOKEEPER
13135,ZOOKEEPER,"Ah, superheroes! Or should I say superzeroes!",ZOOKEEPER
13210,ZOOKEEPER,Of course not. You think I'd show you my lair?...,ZOOKEEPER
13215,ZOOKEEPER,"Our transaction is complete. Come Solomon, to ...",ZOOKEEPER
13133,ZOOKEEPER,"Sorry I'm late, long story. Now everybody hit ...",ZOOKEEPER
10265,ZOIDBERG,"Nothing, I'm leaving. But if you have extra co...",ZOIDBERG
3953,ZOIDBERG,"(shouting) I just wanna talk, it has nothing t...",ZOIDBERG
3967,ZOIDBERG,Do I ask her to mate now?,ZOIDBERG
7927,ZOIDBERG,On margin! Zoidy wanna buy on margin!,ZOIDBERG
3963,ZOIDBERG,"Fry, look what you did, she won't shut up.",ZOIDBERG
3961,ZOIDBERG,(shouting) How was your day?,ZOIDBERG
13047,ZOIDBERG,"I've got just the thing, genuine miracle cream...",ZOIDBERG
3959,ZOIDBERG,Why would I wanna know?,ZOIDBERG
3956,ZOIDBERG,(shouting) You seem malnourished. Are you suff...,ZOIDBERG
3944,ZOIDBERG,Is desire to mate a feeling?,ZOIDBERG
3951,ZOIDBERG,(shouting) I have no idea.,ZOIDBERG
3948,ZOIDBERG,What? Now there's a bird involved?,ZOIDBERG
3946,ZOIDBERG,It's all so complicated with the flowers and t...,ZOIDBERG
3972,ZOIDBERG,"Oh, Edna! (reading) Of all the slimy, gross cr...",ZOIDBERG
3940,ZOIDBERG,But she's not. She's merely the female with th...,ZOIDBERG
3938,ZOIDBERG,Ask her to mate with me.,ZOIDBERG
3936,ZOIDBERG,"Hmm, this ""love"" intrigues me. Teach me to fak...",ZOIDBERG
3933,ZOIDBERG,"(crying) You're right, my stink gland is weak....",ZOIDBERG
3970,ZOIDBERG,(reading) I'd like to propose a toast to ... c...,ZOIDBERG
3989,ZOIDBERG,"Edna, I couldn't stand it any longer. I-- (an...",ZOIDBERG
3977,ZOIDBERG,"I'm confused, Fry. I'm feeling a strange new e...",ZOIDBERG
7915,ZOIDBERG,Zoidy want balloon! Want balloon now! Zoidy wa...,ZOIDBERG
4049,ZOIDBERG,They come to feast after the frenzy. Once my s...,ZOIDBERG
4044,ZOIDBERG,The frenzy is over. How will I ever get rid of...,ZOIDBERG
...,...,...,...
8720,ADLAI,"Leela, you're 999,999 in a million!",ADLAI
8806,ADLAI,"Oh, and I suppose you were fine the way you were?",ADLAI
8804,ADLAI,"Oh, alright. If you really want that one, I ca...",ADLAI
8684,ADLAI,"Hello, Leela. I was in a nearby tailor getting...",ADLAI
8630,ADLAI,Ah-ah. A package is just a box until it's deli...,ADLAI
8686,ADLAI,Just follow the light with your eyes. Perfect!...,ADLAI
8626,ADLAI,Leave Leela alone. She's leading a perfectly n...,ADLAI
8802,ADLAI,"On the other hand, the children bring up a goo...",ADLAI
8799,ADLAI,Her? But there's plenty of normal ones.,ADLAI
8688,ADLAI,"I've never been good with words, which is why ...",ADLAI
8723,ADLAI,"Uh, listen: I just want you all to know your L...",ADLAI
1878,AD-ROCK (SINGING),...tellin' you all it's a...,AD-ROCK (SINGING)
1886,AD-ROCK,"Y'know we're, really not that interested in me...",AD-ROCK
1888,AD-ROCK,That was a thousand years ago. Now we got seven.,AD-ROCK
11632,AARON SR,Low? It was zero you fungo! You went your whol...,AARON SR
11628,AARON SR,No I was better than great. I was the home run...,AARON SR
11634,AARON SR,"You stink lady! Hey Junior, she belongs in the...",AARON SR
11694,AARON SR,"Well, at least you're still the worst football...",AARON SR
11641,AARON JR,OK try it again but this time keep your eye of...,AARON JR
11643,AARON JR,"Hey lady, which one of us is in the hall of fame?",AARON JR
11651,AARON JR,Oh you got that too? I think there's a rash go...,AARON JR
11631,AARON JR,"Well, I have a low batting average.",AARON JR
11635,AARON JR,Forget it. This job's too cushy to give up. A...,AARON JR
11637,AARON JR,Oh I can't help you play better than Tiny Iota...,AARON JR
11626,AARON JR,"I'm not a hologram, though I am crummy. Hank A...",AARON JR
11638,AARON JR,"OK, let's see what you can do.",AARON JR
4966,5-EYES,"Alkazar, why you are so late for our wedding? ...",5-EYES
2756,"""FEMBOT""","Damn chico, one more upgrade and I'll be more ...","""FEMBOT"""
2758,"""FEMBOT""","You couldn't afford it, honey.","""FEMBOT"""
4737,"""COSELL""",Hello and welcome to a remarkable championship...,"""COSELL"""

In [58]:
# 8 characters
df_8ch = df2[(df2.Characters_consolidated == "ZOIDBERG") | (df2.Characters_consolidated == "FRY") 
    | (df2.Characters_consolidated == "LEELA") | (df2.Characters_consolidated == "BENDER")| 
    (df2.Characters_consolidated == "FARNSWORTH") | (df2.Characters_consolidated =='AMY') | 
    (df2.Characters == 'HERMES') | (df2.Characters == 'ZAPP')]

In [59]:
# 6 characters
df_6ch = df2[(df2.Characters_consolidated == "ZOIDBERG") | (df2.Characters_consolidated == "FRY") 
    | (df2.Characters_consolidated == "LEELA") | (df2.Characters_consolidated == "BENDER")| 
    (df2.Characters_consolidated == "FARNSWORTH") | (df2.Characters_consolidated =='AMY')]

In [60]:
# 4 characters
df_4ch = df2[(df2.Characters_consolidated == "FRY") | (df2.Characters_consolidated == "LEELA") | (df2.Characters_consolidated == "BENDER")
   | (df2.Characters_consolidated == "FARNSWORTH")]

In [65]:
df_8ch.to_csv("8characters.csv")
df_6ch.to_csv("6characters.csv")
df_4ch.to_csv("4characters.csv")